server:
  port: 8080
  contextPath: /

driver:
  name: jooq

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/php-crud-api
    username: php-crud-api
    password: php-crud-api

spring.jooq.sql-dialect: MYSQL