server:
  port: 8080
  contextPath: /

driver:
  name: jooq

spring:
  jooq:
    sql-dialect: MYSQL
  datasource:
    url: jdbc:mysql://localhost/php-crud-api
    username: php-crud-api
    password: php-crud-api