server:
  port: 8080
  contextPath: /

spring:
  jooq:
    sql-dialect: POSTGRES
  datasource:
    url: jdbc:postgresql://localhost/php-crud-api
    username: php-crud-api
    password: php-crud-api